spring:
  profiles:
    active:
      - prod

  datasource:
    url: jdbc:postgresql://${PGHOST}/${PGDATABASE}?sslmode=require
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

  messages:
    basename: message

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: ${PORT:80}